name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Report code coverage
        if: always()
        run: |
          echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "| File | Function | Coverage |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|---|" >> $GITHUB_STEP_SUMMARY

          # Use go tool cover to generate coverage per function
          go tool cover -func=coverage.out > coverage.txt

          # Parse the output and append to the step summary
          awk -F'\t+' '
            $1 != "total:" {
              split($1, a, "/")
              filename = a[length(a)]
              sub(/:[0-9]+:/, "", filename) # Remove line number from filename
              print "| " filename " | " $2 " | " $3 " |"
            }
            $1 == "total:" {
              print "\n**Total Coverage:** " $3
            }
          ' coverage.txt >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Check formatting
        run: if [ "$(go fmt ./...)" != "" ]; then echo "Code is not formatted correctly. Please run 'go fmt ./...'"; exit 1; fi

      - name: Run go vet
        run: go vet ./...

  build-mac:
    name: Build Mac Binary (arm64)
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Build Mac Binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -v -o developer-help-tool-cli ./src

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: developer-help-tool-cli-mac-arm64
          path: developer-help-tool-cli
          retention-days: 7
